# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipadd', models.GenericIPAddressField(verbose_name='IP地址')),
                ('time', models.CharField(max_length=50, verbose_name='时间')),
                ('cpu', models.CharField(blank=True, max_length=255, verbose_name='CPU%')),
                ('cpu_detail', models.CharField(blank=True, max_length=255, verbose_name='CPU详情')),
                ('mem', models.CharField(blank=True, max_length=255, verbose_name='内存%')),
                ('mem_detail', models.CharField(blank=True, max_length=255, verbose_name='内存详情')),
                ('disk', models.CharField(blank=True, max_length=255, verbose_name='磁盘%')),
                ('disk_detail', models.CharField(blank=True, max_length=255, verbose_name='磁盘详情')),
                ('net', models.CharField(blank=True, max_length=255, verbose_name='流量 bytes/s')),
                ('net_detail', models.CharField(blank=True, max_length=1000, verbose_name='流量详情')),
                ('tcp', models.CharField(blank=True, max_length=255, verbose_name='tcp连接状态')),
                ('process_down', models.CharField(blank=True, max_length=255, verbose_name='DOWN-进程')),
                ('process_alived', models.CharField(blank=True, max_length=255, verbose_name='Process_UP')),
            ],
        ),
    ]
