# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender', models.CharField(max_length=30, null=True)),
                ('cpu_model', models.CharField(max_length=50, null=True)),
                ('cpu_num', models.CharField(max_length=2, null=True)),
                ('ipaddr', models.GenericIPAddressField()),
                ('hostname', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(to='moniter.Host')),
            ],
        ),
        migrations.DeleteModel(
            name='BasicInfo',
        ),
    ]
