# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0002_auto_20171229_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='cpu_model',
            new_name='m_dim',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cpu_num',
        ),
        migrations.RemoveField(
            model_name='host',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ipaddr',
        ),
        migrations.RemoveField(
            model_name='host',
            name='vender',
        ),
        migrations.AddField(
            model_name='host',
            name='m_logger',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='m_timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='m_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='m_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='project_nick',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='server_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
