# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0003_auto_20171229_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='project_nick',
            field=models.CharField(max_length=50, null=True, verbose_name='what'),
        ),
    ]
