# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0005_auto_20180102_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '数据条目', 'verbose_name_plural': '监控数据详情'},
        ),
        migrations.RemoveField(
            model_name='hostgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='hostgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='group_name',
            field=models.CharField(default=12, max_length=30, verbose_name='监控组'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='host_ips',
            field=models.CharField(default='sss', max_length=300, verbose_name='监控IP列表'),
            preserve_default=False,
        ),
    ]
