# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0006_auto_20180102_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '监控组项', 'verbose_name_plural': '监控组'},
        ),
    ]
