# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_d_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_nick', models.CharField(max_length=250, null=True, verbose_name='项目别名')),
                ('db_nick', models.CharField(max_length=250, null=True, verbose_name='数据库别名')),
                ('db_type', models.CharField(max_length=250, null=True, verbose_name='数据库类型')),
                ('host', models.GenericIPAddressField(verbose_name='主机IP, null=True')),
                ('port', models.CharField(max_length=255, null=True, verbose_name='主机端口号')),
                ('db_name', models.CharField(max_length=255, null=True, verbose_name='数据库名')),
                ('schema_name', models.CharField(max_length=255, null=True, verbose_name='schema号')),
                ('description', models.TextField(null=True, verbose_name='详细描述')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_d_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_nick', models.CharField(max_length=250, null=True, verbose_name='项目别名')),
                ('host_nick', models.CharField(max_length=255, null=True, verbose_name='主机别名')),
                ('host', models.GenericIPAddressField(verbose_name='主机IP, null=True')),
                ('port', models.CharField(max_length=255, null=True, verbose_name='主机端口号')),
                ('server_type', models.CharField(max_length=255, null=True, verbose_name='主机类别')),
                ('description', models.TextField(null=True, verbose_name='详细描述')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_d_real',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_nick', models.CharField(max_length=255, null=True, verbose_name='项目别名')),
                ('host_nick', models.CharField(max_length=255, null=True, verbose_name='主机别名')),
                ('db_nick', models.CharField(max_length=255, null=True, verbose_name='数据库别名')),
                ('m_type', models.CharField(max_length=255, null=True, verbose_name='监控类型')),
                ('m_dim', models.CharField(max_length=255, null=True, verbose_name='监控维度')),
                ('m_value', models.CharField(max_length=255, null=True, verbose_name='监控数据值')),
                ('m_logger', models.TextField(null=True, verbose_name='监控日志')),
                ('m_timestamp', models.DateTimeField(null=True, verbose_name='客户端时间戳')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name_plural': '监控数据详情(m_d_real)',
                'verbose_name': '数据条目',
            },
        ),
        migrations.CreateModel(
            name='m_d_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, null=True, verbose_name='用户类型')),
                ('username', models.CharField(max_length=250, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=250, null=True, verbose_name='密码')),
                ('description', models.TextField(null=True, verbose_name='详细描述')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_d_user_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_nick', models.CharField(max_length=250, null=True, verbose_name='项目别名')),
                ('db_nick', models.CharField(max_length=255, null=True, verbose_name='数据库别名')),
                ('user_group', models.CharField(max_length=250, null=True, verbose_name='用户组')),
                ('username', models.CharField(max_length=250, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=250, null=True, verbose_name='密码')),
                ('description', models.TextField(null=True, verbose_name='详细描述')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_d_user_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_nick', models.CharField(max_length=250, null=True, verbose_name='项目别名')),
                ('host_nick', models.CharField(max_length=255, null=True, verbose_name='主机别名')),
                ('user_group', models.CharField(max_length=250, null=True, verbose_name='用户组')),
                ('username', models.CharField(max_length=250, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=250, null=True, verbose_name='密码')),
                ('description', models.TextField(null=True, verbose_name='详细描述')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=255, null=True, verbose_name='项目别名')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='项目名称')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='项目当前状态')),
                ('content', models.TextField(null=True, verbose_name='详细描述')),
                ('phase', models.CharField(max_length=255, null=True, verbose_name='项目期数')),
                ('resource_id', models.CharField(max_length=255, null=True, verbose_name='资源情况')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_project_checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_id', models.IntegerField(null=True, verbose_name='发送IP')),
                ('project_nick', models.CharField(max_length=255, null=True, verbose_name='项目别名')),
                ('host_nick', models.CharField(max_length=255, null=True, verbose_name='主机别名')),
                ('db_nick', models.CharField(max_length=255, null=True, verbose_name='数据库别名')),
                ('m_type', models.CharField(max_length=255, null=True, verbose_name='监控类型')),
                ('m_dim', models.CharField(max_length=255, null=True, verbose_name='监控维度')),
                ('m_value_type', models.CharField(max_length=255, null=True, verbose_name='监控数据值类型')),
                ('m_value', models.CharField(max_length=255, null=True, verbose_name='监控数据值')),
                ('m_status', models.CharField(max_length=255, null=True, verbose_name='监控状态')),
                ('m_interval_type', models.CharField(max_length=255, null=True, verbose_name='计划任务类型')),
                ('m_interval_time', models.IntegerField(max_length=255, null=True, verbose_name='计划任务时间值')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
                ('Next_checktime', models.DateTimeField(null=True, verbose_name='下次检查时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_nick', models.CharField(max_length=250, null=True, verbose_name='项目别名')),
                ('host_nick', models.CharField(max_length=255, null=True, verbose_name='主机别名')),
                ('db_nick', models.CharField(max_length=255, null=True, verbose_name='数据库别名')),
                ('m_date', models.DateField(null=True, verbose_name='监控日期')),
                ('m_timestamp', models.DateTimeField(null=True, verbose_name='监控时间')),
                ('m_type', models.CharField(max_length=255, null=True, verbose_name='监控类型')),
                ('m_dim', models.CharField(max_length=255, null=True, verbose_name='监控维度')),
                ('m_value', models.CharField(max_length=255, null=True, verbose_name='监控值')),
                ('m_status', models.CharField(max_length=255, null=True, verbose_name='监控状态')),
                ('m_send_status', models.CharField(max_length=255, null=True, verbose_name='发送状态')),
                ('description', models.TextField(null=True, verbose_name='详细描述')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name_plural': '监控报告(m_report)',
                'verbose_name': '数据条目',
            },
        ),
        migrations.CreateModel(
            name='m_report_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(null=True, verbose_name='发送报告IP')),
                ('rule_id', models.IntegerField(null=True, verbose_name='规则ID')),
                ('logger', models.TextField(null=True, verbose_name='详细日志')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_report_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(null=True, verbose_name='发送报告IP')),
                ('send_id', models.IntegerField(null=True, verbose_name='发送IP')),
                ('send_type', models.CharField(max_length=255, null=True, verbose_name='发送类型')),
                ('send_user', models.CharField(max_length=255, null=True, verbose_name='监控发送人')),
                ('send_subject', models.CharField(max_length=255, null=True, verbose_name='监控主题')),
                ('send_message', models.TextField(null=True, verbose_name='发送信息')),
                ('is_send', models.CharField(max_length=255, null=True, verbose_name='是否发送')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='m_rule_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='是否发送')),
                ('user', models.CharField(max_length=255, null=True, verbose_name='监控接收人')),
                ('subject', models.CharField(max_length=255, null=True, verbose_name='主题')),
                ('message', models.TextField(null=True, verbose_name='详细描述')),
                ('timestamp_v', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
    ]
