# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_project_checklist',
            name='m_interval_time',
            field=models.IntegerField(null=True, verbose_name='计划任务时间值'),
        ),
    ]
