# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0002_auto_20180110_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_d_db',
            name='host',
        ),
        migrations.AddField(
            model_name='m_d_db',
            name='host_nick',
            field=models.CharField(max_length=250, null=True, verbose_name='主机别名'),
        ),
    ]
